# Option-1 : creating docker container using command module
---
- hosts: all
  become: true

  tasks:
  - name: creating docker image using docker command
    command: docker run -d --name simple-devops-container -p 8080:8080 simple-devops-image

# Option-2 : creating docker container using docker_container module

  # tasks:
  # - name: create docker container using docker_container module
  #   docker_container:
  #     name: simple-devops-container
  #     image: simple-devops-image
  #     state: present
  #     recreate: yes
  #     ports:
  #       - "8080:8080"
