---
- hosts: all
  become: true
  tasks:
  - name: login to aws ecr
    command: ./aws_login.sh
    args:
      chdir: /opt/docker

  - name: stop if we have old docker container
    command: docker stop hello-container
    ignore_errors: yes
  
  - name: remove stopped docker container
    command: docker rm hello-container
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi 160365781997.dkr.ecr.ap-northeast-2.amazonaws.com/candipay/hello hello:latest
    ignore_errors: yes
  
  # - name: building docker image
  #   command: docker build -t candipay/hello .
  #   args:
  #     chdir: /opt/docker

  - name: pull docker image from ecr
    command: docker pull 160365781997.dkr.ecr.ap-northeast-2.amazonaws.com/candipay/hello:latest
  
  - name: creating container using candipay/hello
    command: docker run -d --name hello-container -p 8080:8080 160365781997.dkr.ecr.ap-northeast-2.amazonaws.com/candipay/hello hello:latest
